[pyprland]
plugins = ["scratchpads", "magnify"] 

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.yazi]
command = "kitty --class scratchpad-large yazi"
lazy = true

[scratchpads.cava]
command = "kitty --class scratchpad-mini cava"
lazy = true
